#!/bin/bash
# Auto-generated by analyze_runs.py
# Project: si-inc/sandbox
# Generated: 2026-02-17 17:09:08

USE_OPTIMAL_RANGES=true
PARALLEL_JOBS=4
START_DATES=("2025-11-05" "2025-11-13" "2025-11-19" "2025-12-01")
END_DATES=("2025-11-11" "2025-11-18" "2025-11-30" "2025-12-17")

# For reference:
START_DATE="2025-11-05"
END_DATE="2025-12-17"
INTERVAL_DAYS=10  # Average only
